listagem=('Lápis',1.75,'Borracha',2.00,'Caderno',15.90,'Estojo',25.00,'Transferidor',4.20)
print('=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=')  
print('LISTAGEM DE PREÇOS')
print('=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=')
print('{}.......................R$ {}'.format(listagem[0], listagem[1]))
print('{}.....................R$ {}'.format(listagem[2], listagem[3]))
print('{}.....................R$ {}'.format(listagem[4],listagem[5]))
print('{}......................R$ {}'.format(listagem[6],listagem[7]))
print('{}.................R$ {}'.format(listagem[8],listagem[9]))
print('=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=')
