valores=(5,4,3,7,8,6,19,20,0,1)
valores1=sorted(valores)
print('Os valores sorteados foram: {}'.format(valores))
print('O maior valor sorteado foi: {} '.format(valores1[9]))
print('O menor valor sorteado foi: {}'.format(valores1[0]))